/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeneficiosRouteImport } from './routes/beneficios'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as MonetizacionRouteImport } from './routes/monetizacion'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as PostularRouteImport } from './routes/postular'
import { Route as PreguntasRouteImport } from './routes/preguntas'
import { Route as ProcesoRouteImport } from './routes/proceso'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiosRoute = BeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const MonetizacionRoute = MonetizacionRouteImport.update({
  id: '/monetizacion',
  path: '/monetizacion',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const PostularRoute = PostularRouteImport.update({
  id: '/postular',
  path: '/postular',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasRoute = PreguntasRouteImport.update({
  id: '/preguntas',
  path: '/preguntas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcesoRoute = ProcesoRouteImport.update({
  id: '/proceso',
  path: '/proceso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beneficios': typeof BeneficiosRoute
  '/contacto': typeof ContactoRoute
  '/monetizacion': typeof MonetizacionRoute
  '/nosotros': typeof NosotrosRoute
  '/postular': typeof PostularRoute
  '/preguntas': typeof PreguntasRoute
  '/proceso': typeof ProcesoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beneficios': typeof BeneficiosRoute
  '/contacto': typeof ContactoRoute
  '/monetizacion': typeof MonetizacionRoute
  '/nosotros': typeof NosotrosRoute
  '/postular': typeof PostularRoute
  '/preguntas': typeof PreguntasRoute
  '/proceso': typeof ProcesoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beneficios': typeof BeneficiosRoute
  '/contacto': typeof ContactoRoute
  '/monetizacion': typeof MonetizacionRoute
  '/nosotros': typeof NosotrosRoute
  '/postular': typeof PostularRoute
  '/preguntas': typeof PreguntasRoute
  '/proceso': typeof ProcesoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beneficios'
    | '/contacto'
    | '/monetizacion'
    | '/nosotros'
    | '/postular'
    | '/preguntas'
    | '/proceso'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beneficios'
    | '/contacto'
    | '/monetizacion'
    | '/nosotros'
    | '/postular'
    | '/preguntas'
    | '/proceso'
  id:
    | '__root__'
    | '/'
    | '/beneficios'
    | '/contacto'
    | '/monetizacion'
    | '/nosotros'
    | '/postular'
    | '/preguntas'
    | '/proceso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeneficiosRoute: typeof BeneficiosRoute
  ContactoRoute: typeof ContactoRoute
  MonetizacionRoute: typeof MonetizacionRoute
  NosotrosRoute: typeof NosotrosRoute
  PostularRoute: typeof PostularRoute
  PreguntasRoute: typeof PreguntasRoute
  ProcesoRoute: typeof ProcesoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficios': {
      id: '/beneficios'
      path: '/beneficios'
      fullPath: '/beneficios'
      preLoaderRoute: typeof BeneficiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monetizacion': {
      id: '/monetizacion'
      path: '/monetizacion'
      fullPath: '/monetizacion'
      preLoaderRoute: typeof MonetizacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postular': {
      id: '/postular'
      path: '/postular'
      fullPath: '/postular'
      preLoaderRoute: typeof PostularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas': {
      id: '/preguntas'
      path: '/preguntas'
      fullPath: '/preguntas'
      preLoaderRoute: typeof PreguntasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proceso': {
      id: '/proceso'
      path: '/proceso'
      fullPath: '/proceso'
      preLoaderRoute: typeof ProcesoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeneficiosRoute: BeneficiosRoute,
  ContactoRoute: ContactoRoute,
  MonetizacionRoute: MonetizacionRoute,
  NosotrosRoute: NosotrosRoute,
  PostularRoute: PostularRoute,
  PreguntasRoute: PreguntasRoute,
  ProcesoRoute: ProcesoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
